name: Test Cron Job

on:
  schedule:
    - cron: '* * * * *'  # Runs every minute

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo current time
        run: |
          echo "This is a scheduled cron job..."
          date -u
