name: Test Cron Job

on:
  schedule:
    - cron: '* * * * *'  # Every minute

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo current time
        run: echo "Current UTC time: $(date -u)"
